services:

  tasktracker-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tasktracker-frontend
    ports:
      - "8081:80"
    networks:
      - tasktracker-network
    healthcheck: 
       test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1/"]
       interval: 30s
       timeout: 10s
       retries: 3
       start_period: 20s
    depends_on: 
      tasktracker-backend:
        condition: service_healthy  

  tasktracker-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tasktracker-backend
#    ports:
#      - "5000:5000"
    networks:
      - tasktracker-network
    environment:
       DB_HOST: "tasktracker-db"
       DB_PORT: "5432"
       DB_NAME: "tasktrackerdb"
       DB_USER: "tasktracker"
       DB_PASSWORD: "tasktracker"    
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:5000/api/health')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on: 
      tasktracker-db:
        condition: service_healthy

  tasktracker-db:
    image: postgres:16
    container_name: tasktracker-db
#    ports: 
#      - "5432:5432"
    networks:
      - tasktracker-network      
    volumes:
      - tasktracker-db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
       POSTGRES_DB: "tasktrackerdb"
       POSTGRES_USER: "tasktracker"
       POSTGRES_PASSWORD: "tasktracker"
    healthcheck:
       test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
       interval: 10s
       timeout: 5s
       retries: 3
       start_period: 10s

volumes:
  tasktracker-db-data:

networks:    
  tasktracker-network:
    driver: bridge





        
